import { underscore } from "../arg/parser.ts";
import { assert } from "../function/assert.ts";
import { parseArgs } from "../function/parse-args.ts";
import { flatten } from "./flatten.ts";
import { load_config } from "./load.ts";

/**
 * Build-time generator: YAML config layers → flattened dotenv artifact
 * consumed by `--env` flags (`deno run`/`deno test`/`deno compile`).
 *
 * Usage: `deno run -A cfg/generate.ts --network=mainnet|testnet [--no-local] [--out=PATH]`
 * Defaults to `.env/banq.{network}.env` with the local overlay included.
 */
const { _, ...opts } = underscore(
  parseArgs(Deno.args, {
    default: {
      no_local: false,
      network: undefined as string | undefined,
      out: undefined as string | undefined,
    },
    boolean: ["no_local"],
    string: ["network", "out"],
  }),
  {},
);

const network = opts.network;
assert(
  typeof network === "string" &&
    (network === "mainnet" || network === "testnet"),
  `Missing or invalid --network: ${network}`,
);

const config = load_config(network, { local: !opts.no_local });
const env = flatten(config);

const out = opts.out ?? `.env/banq.${network}.env`;
const dir = out.slice(0, out.lastIndexOf("/"));
if (dir !== "" && dir !== out) {
  Deno.mkdirSync(dir, { recursive: true });
}
const lines = Object.entries(env)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
Deno.writeTextFileSync(
  out,
  `# generated by cfg/generate.ts — do not edit\n${lines}\n`,
);
console.error(
  `cfg: wrote ${out} (${Object.keys(env).length} keys, local=${!opts
    .no_local})`,
);
